#========================================================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Use Releases file to packaging
# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
#========================================================================================================================
name: 自用源打包脚本

on:
  #对应的是 UTC 时间，需要转换，0 代表北京时间8点，每天10点编译一次
  #关闭则手动编译
  workflow_dispatch:
  #schedule:
    #- cron: 0 2 * * *

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: Config/quicker.config
  #DIY_P1_SH: sh/quick.sh
  DIY_P1_SH: sh/immortalwrt.sh
  DIY_P2_SH: sh/lean2.sh
  DIY_P3_SH: sh/remove.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  OWRT_IP: 192.168.1.110
  OWRT_NAME: package
  OWRT_FILES: package/files
  TZ: Asia/Shanghai

jobs:
  build_package:
    runs-on: ubuntu-latest

    steps:
    - name: 检查项目
      uses: actions/checkout@main
 
    - name: 检查分配的服务器性能
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息："
        echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT 

    - name: 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(cat $GITHUB_WORKSPACE/Ubuntu-2204.txt)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "status=success" >> ${GITHUB_OUTPUT}
          df -Th

    - name: 初始化变量
      run: |
          export OWRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          export OWRT_SOURCE=$(echo $REPO_URL | cut -d '/' -f 5-)
          #export OWRT_TYPE="cortex-a53"

          echo "OWRT_URL=$REPO_URL" >> $GITHUB_ENV
          echo "OWRT_BRANCH=$REPO_BRANCH" >> $GITHUB_ENV
          echo "OWRT_DATE=$OWRT_DATE" >> $GITHUB_ENV
          echo "OWRT_SOURCE=$OWRT_SOURCE" >> $GITHUB_ENV
          echo "OWRT_TYPE=$OWRT_TYPE" >> $GITHUB_ENV
          echo "OWRT_NAME=$OWRT_NAME" >> $GITHUB_ENV
          echo "OWRT_IP=$OWRT_IP" >> $GITHUB_ENV
          echo "DIY_P1_SH=$DIY_P1_SH" >> $GITHUB_ENV
          echo "DIY_P2_SH=$DIY_P2_SH" >> $GITHUB_ENV
          echo "DIY_P3_SH=$DIY_P3_SH" >> $GITHUB_ENV
          echo "OWRT_CFG=$CONFIG_FILE" >> $GITHUB_ENV
          echo "OWRT_FILES=$OWRT_FILES" >> $GITHUB_ENV
    
    - name: 检查脚本
      run: |
        dos2unix ./Scripts/*.sh
        chmod +x ./Scripts/*.sh
        
        #dos2unix ./patch/*.sh
        #chmod +x ./patch/*.sh

    - name: 克隆源仓库
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        
    - name: 打包自定义订阅源
      run: |
        git clone -q --single-branch --depth=1 --branch=master https://github.com/immortalwrt/immortalwrt immortalwrt
        git clone -q --single-branch --depth=1 --branch=master https://github.com/coolsnowwolf/lede lede
        git clone -q --single-branch --depth=1 --branch=main https://github.com/LiBwrt-op/openwrt-6.x breeze303
        
        #建立上传目录
        mkdir -p outfile
        
        #公用函数
        source $GITHUB_WORKSPACE/Scripts/functions.sh
        
        #建立打包目录
        mkdir -p package_file
        cd package_file
        ##########################################################################################
        git clone --depth=1 https://github.com/kenzok8/openwrt-packages feeds/kenzo
        rm -rf feeds/kenzo/taskd
        git_sparse_clone_base_1 main https://github.com/kiddin9/kwrt-packages taskd
        ##########################################################################################
        #师夷长技以制夷类插件A
        #需要删除 feeds/packages/net/homeproxy feeds/kenzo/homeproxy
        #git clone --depth=1 https://github.com/bulianglin/homeproxy package/homeproxy
        git clone --depth=1 https://github.com/immortalwrt/homeproxy package/homeproxy
        
        #需要删除 feeds/luci/applications/luci-app-homeproxy  feeds/kenzo/luci-app-homeproxy
        #git_sparse_clone main https://github.com/kiddin9/kwrt-packages luci-app-homeproxy
        ##########################################################################################
        #师夷长技以制夷类插件B
        git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall-packages package/openwrt-passwall
        rm -rf  package/openwrt-passwall/xray-core
        #git_sparse_clone main https://github.com/kiddin9/kwrt-packages xray-core
        git_sparse_clone main https://github.com/kiddin9/kwrt-packages dns2socks-rust
        merge_package main https://github.com/xiaorouji/openwrt-passwall package luci-app-passwall
        merge_package main https://github.com/xiaorouji/openwrt-passwall2 package luci-app-passwall2
        #merge_package master https://github.com/immortalwrt/luci/ package applications/luci-app-passwall
        merge_package master https://github.com/immortalwrt/luci/ package applications/luci-app-openclash
        git_sparse_clone main https://github.com/kiddin9/kwrt-packages luci-app-bypass
        ##########################################################################################
        #插件需要的依赖
        mkdir -p package/libs
        cp -rf ../lede/package/libs/mbedtls package/libs/mbedtls
        cp -rf ../lede/package/libs/ustream-ssl package/libs/ustream-ssl
        cp -rf ../lede/package/libs/uclient package/libs/uclient
        cp -rf ../lede/package/libs/pcre package/libs/pcre
        ###########################################################################################
        #nss
        #git clone -b main_nss_wifi https://github.com/AgustinLorenzo/nss-packages package/nss-packages
        
        #需要删除 feeds/packages/net/shadowsocks-libev
        #merge_package master https://github.com/immortalwrt/packages package net/shadowsocks-libev
        merge_package master https://github.com/coolsnowwolf/packages package net/shadowsocks-libev
        ##########################################################################################
        git_sparse_clone main https://github.com/kenzok8/small-package dnsforwarder
        git_sparse_clone main https://github.com/kenzok8/small-package v2dat
        git_sparse_clone main https://github.com/kenzok8/small-package shadow-tls
       
        git_sparse_clone main https://github.com/kenzok8/small-package redsocks2
        git_sparse_clone main https://github.com/kenzok8/small-package lua-maxminddb
        git_sparse_clone main https://github.com/kiddin9/kwrt-packages lua-neturl
        git_sparse_clone main https://github.com/kenzok8/small-package luci-app-ssr-plus
        git_sparse_clone main https://github.com/kenzok8/small-package v2ray-core
        git_sparse_clone main https://github.com/kenzok8/small-package dns2tcp
        git_sparse_clone main https://github.com/kenzok8/small-package trojan
        
        #需要删除 package/openwrt-passwall/hysteria
        #git_sparse_clone main https://github.com/kiddin9/kwrt-packages hysteria
        git_sparse_clone main https://github.com/stupidloud/helloworld hysteria
        
        # iStore
        git_sparse_clone main https://github.com/linkease/istore-ui app-store-ui
        git_sparse_clone main https://github.com/linkease/istore luci
        
        #需要删除 feeds/packages/net/mosdns feeds/luci/applications/luci-app-mosdns
        #需要删除 feeds/packages/net/v2ray-geodata
        git clone https://github.com/sbwml/luci-app-mosdns -b v5 package/mosdns
        git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata
        
        #需要删除 feeds/packages/lang/ruby
        merge_package master https://github.com/coolsnowwolf/packages package lang/ruby
        
        #需要删除 feeds/luci/applications/luci-app-turboacc
        git_sparse_clone luci https://github.com/chenmozhijin/turboacc luci-app-turboacc
        
        #需要删除 package/openwrt-passwall/shadowsocks-rust
        git_sparse_clone main https://github.com/kenzok8/small-package shadowsocks-rust
        ##########################################################################################
        git clone --depth=1 https://github.com/esirplayground/luci-app-poweroff package/luci-app-poweroff
        git clone --depth=1 https://github.com/Jason6111/luci-app-netdata package/luci-app-netdata
        git clone --depth=1 https://github.com/destan19/OpenAppFilter package/OpenAppFilter
        git clone --depth=1 -b openwrt-18.06 https://github.com/tty228/luci-app-wechatpush package/luci-app-serverchan
        git clone https://github.com/pexcn/openwrt-chinadns-ng --depth=1 package/openwrt-chinadns-ng
        #git clone https://github.com/rmoyulong/luci-app-omcproxy package/luci-app-omcproxy
        ##########################################################################################
        # 在线用户
        git_sparse_clone main https://github.com/kiddin9/kwrt-packages luci-app-onliner
        sudo chmod -Rf 755 package/luci-app-onliner
        ##########################################################################################
        # msd_lite
        git clone --depth=1 https://github.com/ximiTech/luci-app-msd_lite package/luci-app-msd_lite
        git clone --depth=1 https://github.com/ximiTech/msd_lite package/msd_lite
        
        ##########################################################################################
        # luci-app-amlogic
        git clone https://github.com/ophub/luci-app-amlogic.git package/luci-app-amlogic
        ########################################################################################## 
        # Easytier
        git clone --depth 1 -b main https://github.com/EasyTier/luci-app-easytier.git luci-app-easytier
        mv luci-app-easytier/easytier package/easytier
        mv luci-app-easytier/luci-app-easytier package/luci-app-easytier
        rm -rf luci-app-easytier
        ##########################################################################################
        #immortalwrt 打包需要的插件
        tar zcvfp $GITHUB_WORKSPACE/outfile/immortalwrt.tar.gz .
        ##########################################################################################
        
        #需要删除 feeds/luci/applications/luci-app-kodexplorer
        git_sparse_clone main https://github.com/kiddin9/kwrt-packages luci-app-kodexplorer
        ##########################################################################################
        #需要删除 feeds/packages/net/aria2
        merge_package master https://github.com/immortalwrt/packages package net/aria2
        ###########################################################################################
        #适合lede库的mod_nftables_full 
        rm -rf package/network/utils
        mkdir -p package/network/utils
        cp -rf ../immortalwrt/package/network/utils/fullconenat-nft package/network/utils/fullconenat-nft
        cp -rf ../immortalwrt/package/network/utils/fullconenat package/network/utils/fullconenat
        #cp -rf ../lede/package/network/utils/nftables package/network/utils/nftables
        ###########################################################################################       
        #lede专用 theme
        merge_package master https://github.com/immortalwrt/luci/ package themes/luci-theme-openwrt-2020
        merge_package master https://github.com/immortalwrt/luci/ package themes/luci-theme-openwrt
        ##########################################################################################
        #lede 打包需要的插件
        tar zcvfp $GITHUB_WORKSPACE/outfile/lede.tar.gz .
        ##########################################################################################
        #去掉lede专用
        rm -rf package/luci-theme-openwrt
        rm -rf package/luci-theme-openwrt-2020
        rm -rf package/kernel/cryptodev-linux
        ##########################################################################################
        #luci-theme-argon
        git clone https://github.com/jerrykuku/luci-theme-argon.git --depth=1 package/luci-theme-argon
        git clone https://github.com/jerrykuku/luci-app-argon-config --depth=1 package/luci-app-argon-config
        
        ###########################################################################################
        #openwrt需要的依赖
        mkdir -p package/network/services
        #需要删除 package/network/services/hostapd
        cp -rf ../immortalwrt/package/network/services/hostapd package/network/services/hostapd
        
        #需要删除 feeds/packages/net/curl
        merge_package master https://github.com/coolsnowwolf/packages package net/curl
        ##########################################################################################
        #适合openwrt库的mod_nftables_full 
        rm -rf package/network/utils
        mkdir -p package/network/utils
        cp -rf ../breeze303/package/network/utils/fullconenat-nft package/network/utils/fullconenat-nft
        cp -rf ../breeze303/package/network/utils/fullconenat package/network/utils/fullconenat
        #cp -rf ../lede/package/network/utils/nftables package/network/utils/nftables
        ###########################################################################################
        git_sparse_clone main https://github.com/kiddin9/kwrt-packages cpufreq
        git_sparse_clone main https://github.com/kiddin9/kwrt-packages luci-app-vlmcsd
        merge_package master https://github.com/immortalwrt/packages package net/vlmcsd
        git_sparse_clone main https://github.com/kenzok8/small-package vsftpd
        git_sparse_clone main https://github.com/kiddin9/kwrt-packages luci-app-vsftpd
        git_sparse_clone main https://github.com/kiddin9/kwrt-packages luci-app-usb-printer
        git_sparse_clone main https://github.com/kiddin9/kwrt-packages luci-app-ramfree
        
        #需要删除 feeds/luci/applications/luci-app-zerotier
        git_sparse_clone main https://github.com/kiddin9/kwrt-packages luci-app-zerotier
        ##########################################################################################   
        #openwrt 打包需要的插件
        rm -rf package/libs/mbedtls
        cp -rf ../immortalwrt/package/libs/mbedtls package/libs/mbedtls
        rm -rf package/libs/ustream-ssl
        cp -rf ../immortalwrt/package/libs/ustream-ssl package/libs/ustream-ssl
        tar zcvfp $GITHUB_WORKSPACE/outfile/openwrt.tar.gz .
        ##########################################################################################
        rm -rf package/homeproxy
        rm -rf package/luci-app-homeproxy
        git clone --depth=1 https://github.com/immortalwrt/homeproxy package/homeproxy
        ##########################################################################################
        #openwrt_orther 打包需要的插件
        tar zcvfp $GITHUB_WORKSPACE/outfile/openwrt_orther.tar.gz .
        ##########################################################################################
        rm -rf package/libs
        mkdir -p package/libs
        rm -rf package/network/utils
        cp -rf ../immortalwrt/package/libs/mbedtls package/libs/mbedtls
        rm -rf package/libs/ustream-ssl
        cp -rf ../immortalwrt/package/libs/ustream-ssl package/libs/ustream-ssl
        rm -rf package/libs/uclient
        cp -rf ../immortalwrt/package/libs/uclient package/libs/uclient
        cp -rf ../lede/package/libs/pcre package/libs/pcre
        rm -rf package/network/services/hostapd
        rm -rf package/luci-app-turboacc
        merge_package master https://github.com/coolsnowwolf/luci package applications/luci-app-turboacc
        #openwrt_k2 打包需要的插件
        tar zcvfp $GITHUB_WORKSPACE/outfile/immortalwrt_k2.tar.gz .
        ##########################################################################################
        ###删除所有源 准备备份lede库的mediatek（联发科技）架构
        rm -rf package
        rm -rf base
        rm -rf feeds
        mkdir -p target/linux
        cp -rf ../lede/target/linux/mediatek target/linux
        cp -rf $GITHUB_WORKSPACE/patch/mt7981/filogic.mk target/linux/mediatek/image/filogic.mk
        cp -rf $GITHUB_WORKSPACE/patch/mt7981/mt7981b-cmcc-rax3000me.dts target/linux/mediatek/dts/mt7981b-cmcc-rax3000me.dts
        #mediatek 架构打包
        tar zcvfp $GITHUB_WORKSPACE/outfile/mediatek.gz .        
        ##########################################################################################
        
 
    - name: 生成标签，上传固件
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: union_package
        name: union_package
        body: |
          自用插件源包！
          =============基本信息============

          作者：rmoyulong
          打包时间：${{env.OWRT_DATE}}
        artifacts: outfile/*

    - name: 清理Workflows
      uses: rmoyulong/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 1
